### ISSUE TITLE
Editing a mission can reset the map and mode settings

### ISSUE THREAD

**Issue by NikkoJT** [folkarps/FAMDB#14]
Sometimes, when using the Edit page for a mission, the Map and Mode selections will be reset to Altis and Adversarial. This happens when you open the Edit page, and will be saved with the rest of your edit if you click OK.

I haven't been able to identify a pattern for when this happens.

**Comment by SamLex** [comment]
Notes to self: I _suspect_ this is happening because `LoadMission` in _form.js_ is called immediately, before `GetIslandsList` or `GetMissionTypesList` are called. This creates a race condition between the AJAX call in `LoadMission` and populating the dropdowns with valid values. If the AJAX call "wins" the correct value is discarded as not valid, and then the dropdowns are populated with Altis/Adversarial being the default/first values.

In theory the fix should be as simple as ensuring `LoadMission` is called after `GetIslandsList` and  `GetMissionTypesList`. Testing this will be tricky though due to the intermittent nature of the bug.

**Comment by SamLex** [comment]
Yeah, this seems to have been the issue I'm pretty sure.

I tested by making one script (types.js) take a lot longer to download (by making it 10MB in size). In theory, this should have zero impact. But it reproduced the reported issue 100% of the time. With the fix in #15, the issue no longer occurs in this test.
