### ISSUE TITLE
Full workflow support for GM missions

### ISSUE THREAD

**Issue by SamLex** [folkarps/FAMDB#7]
Split from #1

**Comment by SamLex** [comment]
@NikkoJT My proposed way to support GM missions for now is to add a checkbox to the create/edit mission dialogue (mockup below). When this is checked, a user can interact with the mission as usual. The "move" button will only mark as "ready", not actually copy the PBO. This way GM support is seamless from workflow POV. Thoughts?
![gmsupportmockup](https://user-images.githubusercontent.com/733683/178804889-88e39285-5f3c-404e-bbfa-3417332d7e6a.png)

Implementation note: this is going to be implemented in a way that is very hacky, but works, due to how the current code is structured (spead-out) and it'd be faaaar to much work to refactor (closer to rewrite...) right now.

**Comment by NikkoJT** [comment]
That seems fine. I'd call it "CDLC" rather than specifying GM or SOG as we do have (occasionally) things for other CDLCs too.
I'm hoping that it might be possible to also filter missions by the status of that checkbox. Being able to use a filter to quickly see all CDLC missions, or only non-CDLC missions, would be super helpful for runlist creation.

**Comment by SamLex** [comment]
Added by #12
